
plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.12'
}

version = '0.7.0'

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'nextflow'
    className = 'nextflow.boost.BoostPlugin'
    extensionPoints = [
        'nextflow.boost.BoostConfig',
        'nextflow.boost.BoostExtension',
        'nextflow.boost.BoostObserverFactory'
    ]
}
